### ISSUE TITLE
Negative Pingback

### ISSUE THREAD

**Issue by scysys** [paymentwall/module-whmcs#17]
Negative Pingback is not working in your new version like versions before.

It´s only working in WHMCS, when commenting out

`processCancelable($orderData);` (Line 42)
https://github.com/paymentwall/module-whmcs/blob/master/src/modules/gateways/callback/paymentwall.php

**Comment by pwSupport** [comment]
HI Scysys,

Thanks for your comment,

Our team has already checked the latest version and couldn't reproduce the issue. Are you using mysqli for this? 

Please reply straight here or mail to devsupport@paymentwall.com so we can assist you further.

Regards,
Paymentwall team
