### ISSUE TITLE
Brick Token Saving

### ISSUE THREAD

**Issue by wallydz** [paymentwall/module-whmcs#25]
Hello,
Is there a way to use creditcard.php instead of brickccform.php ? also it would be nice if there is a way to save Credit card token in WHMCS to charge monthly the users

**Comment by miatran** [comment]
Hi wallydz,

Thanks for your interest in our module. As of the moment, we haven't support recurring feature for Brick yet, but it's in the queue for our upcoming releases. 

Regards,
Paymentwall team
