### ISSUE TITLE
Payment not added to invoice

### ISSUE THREAD

**Issue by wallydz** [paymentwall/module-whmcs#26]
<img width="1206" alt="screen shot 2017-03-29 at 15 31 20" src="https://cloud.githubusercontent.com/assets/6662039/24459993/d9dd5228-1494-11e7-84f2-03d2c52a4a01.png">

The payment is never added to the invoice even if it was successful 

For reference b114232217 was never added to invoice
I attached a screenshot of Payment gateway

EDIT : Using WHmcs 7.x and last Paymentwall module 1.4

**Comment by michaelpw** [comment]
Hi,

I've checked that transaction and noticed that initially pingback was failed due to the fact that invoice couldn't be found. We resent the pingback and it has been successful. The invoice should be updated.
