### ISSUE TITLE
hooks crashing site

### ISSUE THREAD

**Issue by Octolus** [paymentwall/module-whmcs#29]
Screenshot: https://i.imgur.com/DSK3yII.png

That happens soon as I upload the hook to hooks.

```text
PHP 7.0.22 (cli) (built: Aug 25 2017 11:52:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.0.0 (), Copyright (c) 2002-2017, by ionCube Ltd.

Server version: 10.1.26-MariaDB MariaDB Server
```

I am using the latest available WHMCS Version.

**Comment by michaelpw** [comment]
Hi,

We doubt that this issue is due to missing Paymentwall library. Could you try uploading the latest release of our module to see if the error still occurs?

https://github.com/paymentwall/module-whmcs/releases/tag/v1.5.3

**Comment by michaelpw** [comment]
Hi @Octolus ,

Have you managed to proceed with the installation of our module?

We couldn't reproduce what you encountered so it would be great if you could drop us an email with more details to michael@paymentwall.com

Thanks!
